# VM NixOS Configuration - Minimal Install
{ config, pkgs, lib, ... }:

{
  imports = [
    # Hardware configuration generated by nixos-generate-config
    ./hardware-configuration.nix
    
    # Use minimal profile
    ../../modules/profiles/minimal.nix
  ];

  # Boot loader - adjust based on your system (UEFI vs BIOS)
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # System basics
  system.stateVersion = "24.11";
  
  networking.hostName = "vm-nixos";
}
