# VM NixOS Configuration - Minimal Install
{ config, pkgs, lib, ... }:

{
  imports = [
    # Hardware configuration generated by nixos-generate-config
    ./hardware-configuration.nix
    
    # Auto-select profile based on hostname
    ../../modules/profiles/minimal.nix
  ];

  # BIOS/Legacy boot with GRUB
  boot.loader.grub.enable = true;
  boot.loader.grub.device = "/dev/sda";  # Adjust if your disk is different (e.g., /dev/vda)

  # System basics
  system.stateVersion = "24.11";
  
  networking.hostName = "vm-nixos";
  
  # VM networking - VirtualBox typically uses NAT by default
  networking.networkmanager.enable = true;
}
