# TW NixOS Configuration - Extended Install
{ config, pkgs, lib, ... }:

{
  imports = [
    # Hardware configuration generated by nixos-generate-config
    ./hardware-configuration.nix

    # Auto-select profile based on hostname  
    ../../modules/profiles/extended.nix
  ];

  # Boot loader - adjust based on your system (UEFI vs BIOS)
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # AMD GPU drivers
  services.xserver.videoDrivers = [ "amdgpu" ];
  hardware.graphics = {
    enable = true;
    enable32Bit = true; # For 32-bit applications like Wine/Steam
  };

  # System basics
  system.stateVersion = "24.11";

  networking.hostName = "tw-nixos";
}
